version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    links:
      - mariadb
    networks:
      - default
    ports:
      - 8070:80

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=lista-telefonica
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql
    networks:
      - default
    ports:
      - 3306:80

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8090:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306



volumes:
  mariadb-data:
