version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/var/www/html"
    ports:
      - 8070:80

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=listatelefonica
      - MYSQL_USER=php-docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./dump:/docker-entrypoint-initdb.d"

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8090:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
