version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    links:
      - mariadb
    networks:
      - default
    ports:
      - 1234:80

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql
    networks:
      - default
    ports:
      - 3306:80

volumes:
  mariadb-data:
